// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetHealthCenter.Infrastructure.Data;

#nullable disable

namespace PetHealthCenter.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Adrres text - street, number, etc.");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Town name");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasComment("ZIP code of the town");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasComment("Addres properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressText = "Tsar Osvobodiltel str. 98",
                            TownName = "Varna",
                            ZipCode = "9000"
                        },
                        new
                        {
                            Id = 2,
                            AddressText = "Slivnitsa blv. 108",
                            TownName = "Varna",
                            ZipCode = "9000"
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int")
                        .HasComment("The address of the customer's office");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Email of the customer");

                    b.Property<bool>("IsCorporate")
                        .HasColumnType("bit")
                        .HasComment("Defines if the customer is corporate or individual");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Name of the customer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasComment("Phone number of the cusotmer");

                    b.Property<string>("ResponsiblePerson")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasComment("Name of the responsible person of the customer's company");

                    b.Property<string>("Uic")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("The Unit Identification Code of the customer's company");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");

                    b.HasComment("Customer information");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Email = "ivan.ivanov@abv.bg",
                            IsCorporate = true,
                            Name = "Ivanov.Inc",
                            PhoneNumber = "099999999",
                            ResponsiblePerson = "Ivan Ivanov",
                            Uic = "1234543421234"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Email = "boris.borisov@abv.bg",
                            IsCorporate = false,
                            Name = "Boris Borisov",
                            PhoneNumber = "0898888888"
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.SpecieType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Name of specie type");

                    b.HasKey("Id");

                    b.ToTable("SpecieTypes");

                    b.HasComment("Type of the animal's specie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hamster"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bird"
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.JobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Job title");

                    b.HasKey("Id");

                    b.ToTable("JobTitles");

                    b.HasComment("Possible job titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Service adviser"
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.OperatingCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Date of the creation of the document");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The number of current document");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PartId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OperatingCards");

                    b.HasComment("Operating card for the current service");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = new Guid("59bff60d-d8d8-4ca8-9da9-48149761e9db"),
                            CustomerId = 1,
                            Date = new DateTime(2022, 12, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            DocumentNumber = "B5466HA12/6/2022 12:00:00 AM",
                            IsActive = true,
                            PartId = 1,
                            ServiceId = 1,
                            PetId = 1
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.OperatingCardParts", b =>
                {
                    b.Property<int>("OperatingCardId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.HasKey("OperatingCardId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("OperatingCardParts");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.OperatingCardHealthService", b =>
                {
                    b.Property<int>("OperatingCardId")
                        .HasColumnType("int");

                    b.Property<int>("HealthServiceId")
                        .HasColumnType("int");

                    b.HasKey("OperatingCardId", "HealthServiceId");

                    b.HasIndex("HealthServiceId");

                    b.ToTable("OperatingCardHealthService");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2")
                        .HasComment("Date of the creation of the order");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Document number");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasComment("Supplier which will deliver the goods");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Orders");

                    b.HasComment("Order of parts properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IssueDate = new DateTime(2022, 12, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Note = "To arrive today",
                            Number = "0001/12/6/2022 12:00:00 AM",
                            SupplierId = 1
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Description of the part");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Manufacturer's name of the part");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The name of the part");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalMpn")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Part's MPN by the car manufacturer");

                    b.Property<decimal>("PriceBuy")
                        .HasPrecision(18, 2)
                        .HasColumnType("money")
                        .HasComment("Delivery price (by the supplier)");

                    b.Property<decimal>("PriceSell")
                        .HasPrecision(18, 2)
                        .HasColumnType("money")
                        .HasComment("Selling price (by the pet health center)");

                    b.Property<int?>("HealthServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasComment("Part's availability");

                    b.Property<int>("ProductComponentId")
                        .HasColumnType("int")
                        .HasComment("Affected part of the animal, where the part may be used");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("HealthServiceId");

                    b.HasIndex("ProductComponentId");

                    b.ToTable("Parts");

                    b.HasComment("Part, stored in the shop's warehouse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cosequin Maximum Strength Plus MSM Joint Supplement for Dogs, 500 Chewable Tablets",
                            ImageUrl = "https://s.turbifycdn.com/aah/healthypetscom/2-pack-cosequin-ds-plus-msm-chewable-tablets-500-count-130.jpg",
                            IsActive = true,
                            Manufacturer = "Cosequin",
                            Name = "Cosequin Maximum Strength Tablets",
                            OriginalMpn = "CHEWDS250-MSM-2PK",
                            PriceBuy = 99.98m,
                            PriceSell = 114.56m,
                            Stock = 4,
                            ProductComponentId = 2
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.HealthService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasComment("Description of the service");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("Name of the service");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("money")
                        .HasComment("Price of the service");

                    b.Property<int>("ProductComponentId")
                        .HasColumnType("int")
                        .HasComment("Affected part of the animal");

                    b.HasKey("Id");

                    b.HasIndex("ProductComponentId");

                    b.ToTable("HealthServices");

                    b.HasComment("Services, offered by pet health center");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Check the common health status and vaccination",
                            IsActive = true,
                            Name = "Diagnosis and vaccination",
                            Price = 65m,
                            ProductComponentId = 4
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int")
                        .HasComment("Address of the supplier's office");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the supplier's company");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Email of the supplier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the supplier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasComment("Phone number of the supplier's office");

                    b.Property<string>("Uic")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Unit Identification Code of the supplier's company");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Suppliers");

                    b.HasComment("Supplier, who delivers parts to the pet health center");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 2,
                            CompanyName = "Garvan EOOD",
                            Email = "garvan@abv.bg",
                            Name = "Garvan",
                            PhoneNumber = "0898888888",
                            Uic = "123456789876"
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.SupplierSparePart", b =>
                {
                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.HasKey("SupplierId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("SupplierSparePart");

                    b.HasComment("Mapping entity between suppliers and parts");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.User.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.User.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("User's first name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("User's last name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasComment("Additional user properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bc5851a-9b57-4d66-99ae-4bfd11f26bd2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e54fccde-0984-45e7-bd1a-14bebfcded6f",
                            Email = "manager_pet_health@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Ivan",
                            IsActive = true,
                            LastName = "Ivanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER_PET_HEALTH@MAIL.COM",
                            NormalizedUserName = "GENERAL_MANAGER",
                            PasswordHash = "AQAAAAEAACcQAAAAELYqdcNgmbE8aU8up16cUOhliyMY8iutF8aLSy0Bi+g/0zPFGPsf6ZsXJsetARdA8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "70c7ac29-fc79-45e7-9d29-b922b7cd7f1e",
                            TwoFactorEnabled = false,
                            UserName = "General_Manager"
                        },
                        new
                        {
                            Id = new Guid("59bff60d-d8d8-4ca8-9da9-48149761e9db"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c35aefcd-4868-4521-b847-43c2ffdd5f24",
                            Email = "doctor_pet_health@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Petar",
                            IsActive = true,
                            LastName = "Petrov",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR_PET_HEALTH@MAIL.COM",
                            NormalizedUserName = "DOCTOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEGOCXPNTjii4efX2qaz5Z1XuRttw7Ze0sY/ns/xKOviVer5SFXTZuTqnMz2qqdG+aw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5755db6a-132e-475d-93b6-d6c2f46f6fad",
                            TwoFactorEnabled = false,
                            UserName = "Doctor"
                        },
                        new
                        {
                            Id = new Guid("4d3bb951-2772-4ae8-b6bb-eb4e80426b0e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5878fada-aeab-4d5f-9988-33391e8c3eb0",
                            Email = "adviser_pet_health@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Georgi",
                            IsActive = true,
                            LastName = "Georgiev",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADVISER_PET_HEALTH@MAIL.COM",
                            NormalizedUserName = "SERVICE_ADVISER",
                            PasswordHash = "AQAAAAEAACcQAAAAEKg2Q8si+Z/6VeJYLtqg4lAe8qOa9hGQJmLZCgAPvLv8ZR6F+xJHmbk1LILkzExTAQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "780e294a-90d6-4b9f-987f-a958b729a0b3",
                            TwoFactorEnabled = false,
                            UserName = "Service_Adviser"
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("SpecieTypeId")
                        .HasColumnType("int")
                        .HasComment("Specie type of the animal");

                    b.Property<DateTime>("FIrstRegistration")
                        .HasColumnType("datetime2")
                        .HasComment("Date of the first registration of the animal");

                    b.Property<string>("IdentificationNUmber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasComment("Identification number of the animal");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Pet origin name");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasComment("Pet subspecies name");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasComment("Specie weight in Kg");

                    b.Property<string>("PetNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasComment("VIN number of the animal");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SpecieTypeId");

                    b.ToTable("Pets");

                    b.HasComment("Pet, owned by customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            SpecieTypeId = 2,
                            FIrstRegistration = new DateTime(2013, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentificationNUmber = "B5466HA",
                            Make = "Labrador",
                            Model = "American",
                            Weight = 272,
                            PetNumber = "12312324125"
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 2,
                            SpecieTypeId = 1,
                            FIrstRegistration = new DateTime(2013, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdentificationNUmber = "B5432PA",
                            Make = "Husky",
                            Model = "Siberian",
                            Weight = 156,
                            PetNumber = "12312324642"
                        });
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.ProductComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of product component");

                    b.HasKey("Id");

                    b.ToTable("ProductComponents");

                    b.HasComment("The components/parts of the animal, which can be affected by the services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Specie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Front and rear axle"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vaccine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Suspenssion system"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tyres and brakes"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Body"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.User.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.User.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Customer", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.OperatingCard", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.User.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId");

                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.HealthService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Customer");

                    b.Navigation("Part");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.OperatingCardParts", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.OperatingCard", "OperatingCard")
                        .WithMany()
                        .HasForeignKey("OperatingCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatingCard");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.OperatingCardHealthService", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.OperatingCard", "OperatingCard")
                        .WithMany()
                        .HasForeignKey("OperatingCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.HealthService", "HealthService")
                        .WithMany()
                        .HasForeignKey("HealthServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatingCard");

                    b.Navigation("HealthService");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Part", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.Order", null)
                        .WithMany("Parts")
                        .HasForeignKey("OrderId");

                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.HealthService", null)
                        .WithMany("Parts")
                        .HasForeignKey("HealthServiceId");

                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.ProductComponent", "ProductComponent")
                        .WithMany()
                        .HasForeignKey("ProductComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductComponent");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.HealthService", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.ProductComponent", "ProductComponent")
                        .WithMany()
                        .HasForeignKey("ProductComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductComponent");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Supplier", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.SupplierSparePart", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.Part", "Part")
                        .WithMany("SupplierSpareParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.Supplier", "Supplier")
                        .WithMany("SupplierSpareParts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Pet", b =>
                {
                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.Customer", "Customer")
                        .WithMany("Pets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetHealthCenter.Infrastructure.Data.Models.SpecieType", "SpecieType")
                        .WithMany()
                        .HasForeignKey("SpecieTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SpecieType");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Customer", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Part", b =>
                {
                    b.Navigation("SupplierSpareParts");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.HealthService", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("PetHealthCenter.Infrastructure.Data.Models.Supplier", b =>
                {
                    b.Navigation("SupplierSpareParts");
                });
#pragma warning restore 612, 618
        }
    }
}
